### ISSUE TITLE
Add raw data to the raw repository

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/tangclassifiers#1]
@marctang, you can upload the raw data file you sent me before to the repository "raw/". From there, we'll take it, manipulate it slightly with the python cldf package, and then make a coherent CLDF repo (which you can read with R as well).

For sharing your code, you can place it into a folder `scripts` (I didn't make that yet).

**Comment by marctang** [comment]
Cool! I just updated the data in raw/ and created scripts/ with the code
