### ISSUE TITLE
Sources of the data

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/tangclassifiers#3]
@marctang, can you point me to particular sources, or where the data all aggregated from the same source?

**Comment by marctang** [comment]
I assume you mean the sources for each language in bibtex format? if yes, the original data did not have it all imported in bibtex, but it can be done during the incoming days. I assume what is needed is the .bib file with all the sources and their index in a column of the raw data? e.g., for 

@book{zhang_classifier_2013,
	address = {Berlin},
	title = {Classifier structures in {Mandarin} {Chinese}},
	urldate = {2016-08-24},
	publisher = {Mouton de Gruyter},
	author = {Zhang, Niina Ning},
	year = {2013},
	file = {2012_Zhang_Numeral classifier structures.pdf:/home/marctang/Zotero/storage/6N5U7K8I/2012_Zhang_Numeral classifier structures.pdf:application/pdf}
}

If a language uses this reference, mention it as zhang_classifier_2013 in the source column of the raw data?

**Comment by LinguList** [comment]
exactly! If you can do so, this would be great. It should be placed,
according to our conventions, into the folder "sources.bib".

**Comment by marctang** [comment]
Great! I just added sources.bib in raw/, is that the correct location?

**Comment by LinguList** [comment]
super.

**Comment by LinguList** [comment]
I added them now, you can check the code I just pushed.
