### ISSUE TITLE
duplicate language name 

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/tangclassifiers#4]
```
$ cldf validate cldf/StructureDataset-metadata.json 
WARNING cldf/languages.csv:145 duplicate primary key: Semandang
```

**Comment by marctang** [comment]
changed the duplicate names and updated their Glottocode to 
Samandang nucl1557
Onya Darat sema1269

**Comment by LinguList** [comment]
Nice. It is also nice to see that we have already found a little problem
by simply converting to cldf. This happens often, since cldf checks for
very rough simple requirements one may easily forget...

**Comment by marctang** [comment]
Totally agree on this !
