### ISSUE TITLE
first code, test

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/tangclassifiers#5]
@marctang, I added a first code example, should be straightforward, only sources need to be handled once available.

do the following: make a fresh virtual environment and then install cldfbench:

```
$ pip install cldfbench
```

I think this should include all requirements needed now. Then you just do:

```
$ python convert.py
```

And this will create the cldf dataset. You can check the result in the folder `cldf/`. 

If you check the Python script, I left some `+++` there, where you can fill in information. Let me know if anything is unclear.

To check the data, run:

```
$ cldf validate cldf/StructureDataset-metadata.json
```

**Comment by marctang** [comment]
Cool! Thanks! i just tried it after I added the +++ info, and it seems to work properly through the virtual environment. I also added sources.bib in raw/.
