### ISSUE TITLE
Quick question on using this dataset in clld

### ISSUE THREAD

**Issue by marctang** [cldf-datasets/tangclassifiers#8]
If I may use the opportunity to ask for more advice :-P, here it is: I am also planning to deploy some other databases with the clld framework. Now, thanks to you guys, I will be able to format myself first these databases according to the clfd format and add them in the cldf-datasets.

For using clld, I followed the explanation online and I can get the default example to work. However, I am less sure about how I could, for example, feed the tangclassifiers cldf dataset to it and deploy it online with clld? https://clld.readthedocs.io/en/latest/tutorial.html#populating-the-database Sorry in advance if it is a stupid question @@

**Comment by xrotwang** [comment]
@marctang just added a `CodeTable` (see https://github.com/cldf-datasets/tangclassifiers/commit/de6e87bda980ee77423d87723f9fba376c6f01ec#diff-d9858e8d7e38dec098e24d087bd3c536). With this output, `clld initdb` works (on my end). Will put together a recipe in the [CLDF cookbook](https://github.com/cldf/cookbook) how to do that.

**Comment by xrotwang** [comment]
@marctang regarding CLDF an R: @SimonGreenhill has an [R library for reading CLDF](https://github.com/SimonGreenhill/rcldf). Fleshing this out to have the full scope of functionalities of `pycldf` might be cool. But to be honest, I'd prefer even R users learn the bit of python necessary to read and write files, since for these things python seems to be the more mature language (e.g. regarding Unicode, paths on different OSs, etc.).

**Comment by marctang** [comment]
@xrotwang Super thanks! Well noted for the R library. I will do what you suggest and get familiar with both Python and R for this. Thanks also for adding the CodeTable, like this I'll be able to add it for other datasets in the future too :-) I just tested `clld initdb` with `pserve --reload development.ini` to test it and it works! Yay!

Two more questions though @@. Sorry again for being annoying, I'll pay back by doing my best to teach other people how to do this so that you don't get swarmed by the same questions.

1) for CLDF: the feature values seem to be duplicated. For both features (sortal classifier and morphosyntactic plural), the value became the one of sortal classifiers, e.g., in the original data, Ainu and Abun are sortalclassifiers = yes and morphosyntacticplural = no, but in values.csv they are sortalclassifiers = yes and morphosyntacticplural = yes. When I checked the details in values.csv, it seems that the morphosyntactic plural feature has exactly the same values as the sortal classifier feature.

2) for CLLD: in the html deployed locally, everything is correct, except the source part, in which the references do not show up:

![Screenshot from 2020-06-11 09-07-58](https://user-images.githubusercontent.com/27649520/84356396-6682a880-abc4-11ea-8b58-fcf6e22d3ea7.png)

and when I click on an individual one, I get:

![Screenshot from 2020-06-11 09-08-16](https://user-images.githubusercontent.com/27649520/84356479-89ad5800-abc4-11ea-973f-808d42d0a416.png)

**Comment by xrotwang** [comment]
@marctang re CLDF: Good catch! Will check and add some consistency checking (that's what `test.py` is for, which is particularly important for larger datasets where eye-balling isn't an option anymore).

**Comment by xrotwang** [comment]
@marctang re sources in clld app: See https://github.com/clld/clld/issues/212

**Comment by xrotwang** [comment]
@marctang At https://github.com/cldf-datasets/tangclassifiers/commit/5a7387860bb17a803bc372bc236d1d7cdbf41729#diff-b284a28710cce90d9d9be3a7f4cabc8e you can see an example how you'd do some consistency checking for the CLDF data. This is mainly to prevent regressions introduced by fiddling with the code in `cmd_makecldf`. 

https://github.com/cldf-datasets/tangclassifiers/commit/5a7387860bb17a803bc372bc236d1d7cdbf41729#diff-354f30a63fb0907d4ad57269548329e3 also hooks these tests up with travis, i.e. whenever a change is pushed to the repository, the committer will get an email notification if tests no longer pass.

**Comment by marctang** [comment]
Thanks! The output is correct now! Well noted also for the examples of checking the data. For the sources in clld, I replied in the other issue you opened, so I'll close the current issue.

> @marctang At [5a73878#diff-b284a28710cce90d9d9be3a7f4cabc8e](https://github.com/cldf-datasets/tangclassifiers/commit/5a7387860bb17a803bc372bc236d1d7cdbf41729#diff-b284a28710cce90d9d9be3a7f4cabc8e) you can see an example how you'd do some consistency checking for the CLDF data. This is mainly to prevent regressions introduced by fiddling with the code in `cmd_makecldf`.
> 
> [5a73878#diff-354f30a63fb0907d4ad57269548329e3](https://github.com/cldf-datasets/tangclassifiers/commit/5a7387860bb17a803bc372bc236d1d7cdbf41729#diff-354f30a63fb0907d4ad57269548329e3) also hooks these tests up with travis, i.e. whenever a change is pushed to the repository, the committer will get an email notification if tests no longer pass.

**Comment by xrotwang** [comment]
@marctang If you find the time, you could review https://github.com/cldf/cookbook/blob/master/recipes/clld/README.md - which should be rather similar to what you did to get started with clld.

**Comment by marctang** [comment]
Awesome! That's indeed quite similar and even faster in a way since it is directly from the CLDF online data! Thanks!
